import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { buildNewspaperViewerHtml } from '../src/components/news/NewspaperEditionViewer';

const [, , inputPath, outputPath] = process.argv;
if (!inputPath || !outputPath) {
  throw new Error('Usage: tsx apps/league-sites/scripts/build-hockey-life-times-viewer-harness.ts <frozen-srcdoc.html> <output-directory>');
}

const sha256 = (value: string) => createHash('sha256').update(value).digest('hex');
const escapeAttribute = (value: string) => value
  .replaceAll('&', '&amp;')
  .replaceAll('"', '&quot;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;');

function pageSegments(html: string) {
  const pages: string[] = [];
  const starts = /<section\b[^>]*class=["'][^"']*\bnewspaper-page\b[^"']*["'][^>]*>/gi;
  for (const match of html.matchAll(starts)) {
    let depth = 1;
    const sections = /<section\b[^>]*>|<\/section\s*>/gi;
    sections.lastIndex = (match.index ?? 0) + match[0].length;
    let token: RegExpExecArray | null;
    while ((token = sections.exec(html))) {
      depth += /^<section\b/i.test(token[0]) ? 1 : -1;
      if (depth === 0) {
        pages.push(html.slice(match.index ?? 0, sections.lastIndex));
        break;
      }
    }
  }
  return pages;
}

function hostPage(label: string, srcdoc: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${label}</title><style>*{box-sizing:border-box}html,body{margin:0;background:#111;color:#fff;font-family:-apple-system,sans-serif}.controls{height:52px;display:flex;align-items:center;gap:12px;padding:8px 12px;background:#15202b}.controls a{color:#fff;border:1px solid #8190a0;border-radius:7px;padding:7px 10px;text-decoration:none}.controls output{margin-left:auto;font-weight:700}iframe{display:block;width:368px;height:716px;max-width:100vw;border:0;background:#292927}</style></head><body><nav class="controls" aria-label="Fixture zoom controls"><a href="fit.html">Fit</a><a href="zoom-65.html">Zoom 65%</a><output>${label}</output></nav><iframe title="Hockey Life Times corrected production-path fixture" sandbox="" srcdoc="${escapeAttribute(srcdoc)}"></iframe></body></html>`;
}

async function main() {
  const frozen = await readFile(inputPath, 'utf8');
  const pages = pageSegments(frozen);
  if (pages.length !== 5) throw new Error(`Expected five frozen pages, found ${pages.length}`);

  const fit = buildNewspaperViewerHtml(frozen, null);
  const zoom = buildNewspaperViewerHtml(frozen, 0.65);
  for (const [name, output] of [['fit', fit], ['zoom-65', zoom]] as const) {
    if (!pages.every((page) => output.includes(page))) throw new Error(`${name} changed a frozen page segment`);
    if ((output.match(/class="newspaper-page-wrap"/g) ?? []).length !== 5) throw new Error(`${name} wrapper count is not five`);
  }

  await mkdir(outputPath, { recursive: true });
  await writeFile(path.join(outputPath, 'fit-srcdoc.html'), fit);
  await writeFile(path.join(outputPath, 'zoom-65-srcdoc.html'), zoom);
  await writeFile(path.join(outputPath, 'fit.html'), hostPage('Fit', fit));
  await writeFile(path.join(outputPath, 'zoom-65.html'), hostPage('Zoom 65%', zoom));

  const imageUrls = [...frozen.matchAll(/<img\b[^>]*\bsrc="([^"]+)"/gi)].map((match) => match[1]);
  const manifest = {
    schemaVersion: 1,
    sourceCommit: process.env.HLT_SOURCE_COMMIT ?? 'set HLT_SOURCE_COMMIT when generating',
    sourceModule: 'apps/league-sites/src/components/news/NewspaperEditionViewer.tsx#buildNewspaperViewerHtml',
    input: { path: inputPath, bytes: Buffer.byteLength(frozen), sha256: sha256(frozen) },
    invariants: {
      pageCount: pages.length,
      opaqueSandbox: true,
      pageSegmentsPreservedVerbatim: true,
      imageUrlCount: imageUrls.length,
      imageUrlsSha256: sha256(JSON.stringify(imageUrls)),
      pages: pages.map((page, index) => ({ page: index + 1, bytes: Buffer.byteLength(page), sha256: sha256(page) })),
    },
    outputs: {
      fit: { file: 'fit-srcdoc.html', bytes: Buffer.byteLength(fit), sha256: sha256(fit) },
      zoom65: { file: 'zoom-65-srcdoc.html', bytes: Buffer.byteLength(zoom), sha256: sha256(zoom) },
    },
  };
  await writeFile(path.join(outputPath, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  await writeFile(path.join(outputPath, 'PARENT-HARNESS.md'), `# Parent-owned HLT source-bound fixture\n\nGenerated by the committed production-path harness at source commit \`${manifest.sourceCommit}\`. The exact frozen input is recorded in \`manifest.json\`; every original page segment and image URL is preserved. The only srcdoc delta is the production viewer wrapper/style generated by \`buildNewspaperViewerHtml\`.\n\nServe this directory with the parent's existing approved loopback-only static server, then open \`/fit.html\` and \`/zoom-65.html\`. Both pages use a 368 x 716 iframe with unchanged opaque \`sandbox=""\`; no iframe script or same-origin permission is added. No server is started by the generator.\n\nRegenerate from the worktree root:\n\n\`\`\`sh\nHLT_SOURCE_COMMIT=$(git rev-parse HEAD) node_modules/.bin/tsx apps/league-sites/scripts/build-hockey-life-times-viewer-harness.ts <frozen-srcdoc.html> <output-directory>\n\`\`\`\n`);
  process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
