import React from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';

import type { NewspaperBrief, NewspaperEdition } from '../lib/newspaperReader';
import colors from '../theme/colors';

function Artwork({ uri, label }: { uri?: string; label: string }) {
  return uri
    ? <Image source={{ uri }} accessibilityLabel={label} alt={label} resizeMode="cover" style={styles.artwork} />
    : <View accessibilityLabel={`${label}; artwork not supplied`} style={styles.artFallback}><Text style={styles.fallbackSmall}>HOCKEY LIFE</Text><Text style={styles.fallbackLarge}>TIMES</Text></View>;
}

function SectionTitle({ children, accentColor }: { children: React.ReactNode; accentColor: string }) {
  return <Text accessibilityRole="header" style={[styles.sectionTitle, { borderBottomColor: accentColor }]}>{children}</Text>;
}

function Briefs({ title, items, accentColor }: { title: string; items: NewspaperBrief[]; accentColor: string }) {
  return <View style={styles.section}><SectionTitle accentColor={accentColor}>{title}</SectionTitle>{items.length ? items.map((item, index) => <View key={`${item.headline}:${index}`} style={styles.brief}>
    {item.imageUrl ? <Artwork uri={item.imageUrl} label={item.headline} /> : null}<View style={styles.grow}><Text style={styles.cardTitle}>{item.headline}</Text><Text style={styles.copy}>{item.body}</Text></View>
  </View>) : <Text style={styles.muted}>No {title.toLowerCase()} item was supplied.</Text>}</View>;
}

export default function NativeNewspaperEdition({ edition, accentColor }: { edition: NewspaperEdition; accentColor: string }) {
  return <View testID="native-newspaper-edition" accessibilityLabel={`${edition.title} issue ${edition.issueNumber}`} style={styles.paper}>
    <View style={[styles.masthead, { borderColor: accentColor }]}><Text style={[styles.kicker, { color: accentColor }]}>PUBLISHED EDITION · ISSUE {edition.issueNumber}</Text><Text accessibilityRole="header" style={styles.mastTitle}>Hockey Life Times</Text><Text style={styles.mastMeta}>{edition.leagueName} · {edition.seasonName}{'\n'}{edition.periodStart} to {edition.periodEnd}</Text></View>
    <View style={styles.section}><Text style={[styles.kicker, { color: accentColor }]}>THE BIG STORY</Text><Text accessibilityRole="header" style={styles.leadTitle}>{edition.lead.headline}</Text><Text style={styles.dek}>{edition.lead.dek}</Text><Artwork uri={edition.lead.imageUrl} label={edition.lead.headline} />{edition.lead.caption ? <Text style={styles.caption}>{edition.lead.caption}</Text> : null}{edition.lead.body.map((paragraph, index) => <Text key={index} style={styles.copy}>{paragraph}</Text>)}</View>
    <View style={styles.section}><SectionTitle accentColor={accentColor}>This Week on the Ice</SectionTitle>{edition.games.map((game) => <View key={game.gameId} style={styles.card}><Text style={styles.cardTitle}>{game.headline}</Text><View style={styles.score}><View style={styles.team}>{game.awayTeam.logoUrl ? <Image source={{ uri: game.awayTeam.logoUrl }} accessibilityLabel={`${game.awayTeam.name} logo`} alt={`${game.awayTeam.name} logo`} resizeMode="contain" style={styles.logo} /> : null}<Text style={styles.teamName}>{game.awayTeam.name}</Text><Text style={[styles.scoreValue, { color: accentColor }]}>{game.awayScore}</Text></View><Text style={styles.final}>FINAL</Text><View style={styles.team}>{game.homeTeam.logoUrl ? <Image source={{ uri: game.homeTeam.logoUrl }} accessibilityLabel={`${game.homeTeam.name} logo`} alt={`${game.homeTeam.name} logo`} resizeMode="contain" style={styles.logo} /> : null}<Text style={styles.teamName}>{game.homeTeam.name}</Text><Text style={[styles.scoreValue, { color: accentColor }]}>{game.homeScore}</Text></View></View>{game.imageUrl ? <Artwork uri={game.imageUrl} label={game.headline} /> : null}{game.body.map((paragraph, index) => <Text key={index} style={styles.copy}>{paragraph}</Text>)}<Text style={styles.subhead}>Names on the scoresheet</Text>{game.contributors.length ? game.contributors.map((player) => <Text key={player.playerId} style={styles.statLine}>{player.name} · {player.teamName} · {player.goals}G {player.assists}A {player.points}P</Text>) : <Text style={styles.muted}>No individual contributors were supplied.</Text>}</View>)}</View>
    <View style={styles.section}><SectionTitle accentColor={accentColor}>Three Stars of the Week</SectionTitle>{edition.stars.map((star, index) => <View key={star.playerId} style={styles.card}>{star.illustrationUrl || star.photoUrl ? <Artwork uri={star.illustrationUrl || star.photoUrl} label={`${star.name}, ${star.teamName}`} /> : null}<Text style={[styles.kicker, { color: accentColor }]}>#{index + 1} · {star.teamName}</Text><Text style={styles.cardTitle}>{star.name}</Text><Text style={styles.statLine}>{star.goals} goals · {star.assists} assists · {star.points} points</Text><Text style={styles.copy}>{star.reason}</Text></View>)}</View>
    <View style={styles.section}><SectionTitle accentColor={accentColor}>This Week by the Numbers</SectionTitle><View style={styles.numberGrid}>{edition.numbers.filter((item) => !/\b(?:source\s+warnings?|warning\s+count)\b/i.test(item.label)).map((item, index) => <View key={`${item.label}:${index}`} style={styles.number}><Text style={[styles.numberValue, { color: accentColor }]}>{item.value}</Text><Text style={styles.numberLabel}>{item.label}</Text>{item.detail ? <Text style={styles.muted}>{item.detail}</Text> : null}</View>)}</View></View>
    <View style={styles.section}><SectionTitle accentColor={accentColor}>Standings</SectionTitle>{edition.standings.map((row, index) => <View key={row.teamId} style={styles.standing}>{row.logoUrl ? <Image source={{ uri: row.logoUrl }} accessibilityLabel={`${row.name} logo`} alt={`${row.name} logo`} resizeMode="contain" style={styles.logo} /> : null}<Text style={styles.place}>{index + 1}</Text><View style={styles.grow}><Text style={styles.teamName}>{row.name}</Text><Text style={styles.statLine}>{row.gp} GP · {row.w}-{row.l}-{row.otl}-{row.t} · {row.gf} GF · {row.ga} GA</Text></View><Text style={[styles.points, { color: accentColor }]}>{row.pts} PTS</Text></View>)}<Text style={styles.copy}>{edition.standingsNote}</Text></View>
    <Briefs title="The Heater" items={edition.hot} accentColor={accentColor} />
    <Briefs title="The Cold Tub" items={edition.cold} accentColor={accentColor} />
    <View style={styles.section}><SectionTitle accentColor={accentColor}>Next Week</SectionTitle>{edition.upcoming.length ? edition.upcoming.map((game) => <View key={game.gameId} style={styles.card}><Text style={styles.cardTitle}>{game.headline}</Text><Text style={styles.statLine}>{game.awayName} at {game.homeName} · {new Date(game.scheduledAt).toLocaleString('en-CA')}{game.venue ? ` · ${game.venue}` : ''}</Text><Text style={styles.copy}>{game.body}</Text></View>) : <Text style={styles.copy}>{edition.upcomingNote}</Text>}</View>
    {edition.aroundRink ? <Briefs title="Around the Rink" items={edition.aroundRink} accentColor={accentColor} /> : null}
    <View style={styles.section}><SectionTitle accentColor={accentColor}>Source Notes</SectionTitle><Text style={styles.muted}>Verified {edition.source.verifiedAt}{edition.source.standingsAsOf ? ` · standings as of ${edition.source.standingsAsOf}` : ''}</Text>{edition.source.warnings.map((warning, index) => <Text key={index} style={styles.copy}>• {warning}</Text>)}</View>
  </View>;
}

const styles = StyleSheet.create({
  paper: { width: '100%', gap: 24, marginTop: 18, padding: 16, borderRadius: 20, backgroundColor: '#F2E9D5' },
  masthead: { borderTopWidth: 5, borderBottomWidth: 2, paddingVertical: 12 }, mastTitle: { color: '#181712', fontSize: 36, lineHeight: 41, fontWeight: '900' }, mastMeta: { color: '#514B42', fontSize: 13, lineHeight: 19, marginTop: 5 },
  kicker: { fontSize: 10, lineHeight: 15, fontWeight: '900', letterSpacing: 1.4, textTransform: 'uppercase' }, section: { gap: 10 }, sectionTitle: { color: '#181712', fontSize: 25, lineHeight: 31, fontWeight: '900', borderBottomWidth: 4, paddingBottom: 6 },
  leadTitle: { color: '#181712', fontSize: 34, lineHeight: 38, fontWeight: '900' }, dek: { color: '#363129', fontSize: 18, lineHeight: 26, fontWeight: '700' }, copy: { color: '#24211B', fontSize: 17, lineHeight: 27 }, caption: { color: '#625B50', fontSize: 12, lineHeight: 17, fontStyle: 'italic' },
  artwork: { width: '100%', aspectRatio: 16 / 9, borderRadius: 10, backgroundColor: colors.bgElevated }, artFallback: { width: '100%', aspectRatio: 16 / 9, borderRadius: 10, borderWidth: 1, borderColor: '#867C6B', alignItems: 'center', justifyContent: 'center', backgroundColor: '#DDD0B7' }, fallbackSmall: { color: '#181712', fontSize: 13, fontWeight: '900', letterSpacing: 2 }, fallbackLarge: { color: '#A4161A', fontSize: 30, fontWeight: '900', letterSpacing: 2 },
  card: { gap: 9, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#9C9383' }, cardTitle: { color: '#181712', fontSize: 23, lineHeight: 28, fontWeight: '900' }, score: { gap: 8, paddingVertical: 8, borderTopWidth: 2, borderBottomWidth: 2, borderColor: '#181712' }, team: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8 }, logo: { width: 34, height: 34 }, teamName: { flex: 1, color: '#181712', fontSize: 15, lineHeight: 20, fontWeight: '800' }, scoreValue: { fontSize: 28, fontWeight: '900' }, final: { color: '#514B42', fontSize: 10, fontWeight: '900', textAlign: 'center' }, subhead: { color: '#181712', fontSize: 16, fontWeight: '900', textTransform: 'uppercase' }, statLine: { color: '#514B42', fontSize: 13, lineHeight: 19 }, muted: { color: '#625B50', fontSize: 13, lineHeight: 19 },
  numberGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, number: { minWidth: '46%', flex: 1, padding: 11, borderWidth: 1, borderColor: '#9C9383' }, numberValue: { fontSize: 28, fontWeight: '900' }, numberLabel: { color: '#181712', fontSize: 13, fontWeight: '900', textTransform: 'uppercase' },
  standing: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: 1, borderBottomColor: '#9C9383' }, place: { color: '#625B50', fontWeight: '900' }, grow: { flex: 1, minWidth: 0 }, points: { fontSize: 15, fontWeight: '900' }, brief: { gap: 10, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#9C9383' },
});
